#if !canImport(ObjectiveC)
import XCTest

extension elp2000_82b_tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__elp2000_82b_tests = [
        ("testELP2000", testELP2000),
    ]
}

extension time_tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__time_tests = [
        ("testDateTime", testDateTime),
        ("testIsLeap", testIsLeap),
    ]
}

extension vsop87_tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__vsop87_tests = [
        ("testEarth", testEarth),
        ("testJupiter", testJupiter),
        ("testMars", testMars),
        ("testMercury", testMercury),
        ("testNeptune", testNeptune),
        ("testSaturn", testSaturn),
        ("testSun", testSun),
        ("testUranus", testUranus),
        ("testVenus", testVenus),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(elp2000_82b_tests.__allTests__elp2000_82b_tests),
        testCase(time_tests.__allTests__time_tests),
        testCase(vsop87_tests.__allTests__vsop87_tests),
    ]
}
#endif
